# Generated by Django 6.1 on 2026-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='secret_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
