# Generated by Django 6.1 on 2026-09-11 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licensing', '0002_auditreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remediation_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('EXECUTING', 'Executing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled back')], default='PROPOSED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_requests', to='licensing.auditreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
