# Generated by Django 6.1 on 2026-09-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0002_remediationrequest_result_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediationrequest',
            name='target_volume',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
