# Generated by Django 6.1 on 2026-09-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remediation', '0003_remediationrequest_target_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediationrequest',
            name='execution_mode',
            field=models.CharField(choices=[('DRY_RUN', 'Dry-run'), ('REAL', 'Real')], default='DRY_RUN', max_length=20),
        ),
    ]
